### ISSUE TITLE
Feedback on your assignment

### ISSUE THREAD

**Issue by larnsce** [ghclass-demo/hw01-everyone#3]
Hi @cat-615 and @brianmsm! Well done on your first assignment. You will received your grads via Email.

**Comment by cat-615** [comment]
Thanks for the feedback @larnsce

**Comment by brianmsm** [comment]
Thanks very much! I like github!

**Comment by larnsce** [comment]
> 
> 
> Thanks very much! I like github!

Yes, it's great!

**Comment by larnsce** [comment]
I will close the issue now,
